export interface RoomEmojiItem {
  emoji: string;
  name: string;
  cat: 'tools' | 'food' | 'transport' | 'characters' | 'nature' | 'activities';
}

export const ROOM_EMOJI_LIST: RoomEmojiItem[] = [
  // Tools & Objects
  { emoji: '🛠️', name: 'tools hammer wrench work build craft', cat: 'tools' },
  { emoji: '🔧', name: 'wrench spanner fix repair mechanic tool', cat: 'tools' },
  { emoji: '🔨', name: 'hammer construction build nail tool', cat: 'tools' },
  { emoji: '⚙️', name: 'gear settings engine mechanism cog machine', cat: 'tools' },
  { emoji: '💡', name: 'bulb idea light innovation solution insight', cat: 'tools' },
  { emoji: '💻', name: 'laptop computer code tech coding screen', cat: 'tools' },
  { emoji: '📱', name: 'phone mobile smartphone app tech screen', cat: 'tools' },
  { emoji: '📐', name: 'ruler triangle angle design architecture math', cat: 'tools' },
  { emoji: '📏', name: 'ruler measure length dimension geometry', cat: 'tools' },
  { emoji: '🎨', name: 'palette art paint design color studio', cat: 'tools' },
  { emoji: '✏️', name: 'pencil sketch write draw note draft', cat: 'tools' },
  { emoji: '📦', name: 'box package parcel delivery storage supply', cat: 'tools' },
  { emoji: '📷', name: 'camera photo photograph lens capture video', cat: 'tools' },
  { emoji: '🔑', name: 'key access security lock secret password', cat: 'tools' },
  { emoji: '🧭', name: 'compass navigate navigation direction explore', cat: 'tools' },
  { emoji: '⏰', name: 'clock alarm timer schedule deadline morning', cat: 'tools' },
  { emoji: '🔭', name: 'telescope astronomy science look search future', cat: 'tools' },
  { emoji: '🔬', name: 'microscope science laboratory research biology', cat: 'tools' },
  { emoji: '🔋', name: 'battery power energy charge electrical', cat: 'tools' },
  // Food & Drinks
  { emoji: '🍕', name: 'pizza food slice cheese Italian lunch dinner', cat: 'food' },
  { emoji: '🍔', name: 'burger hamburger fastfood sandwich grill', cat: 'food' },
  { emoji: '🍟', name: 'fries potato chips fastfood snack', cat: 'food' },
  { emoji: '☕', name: 'coffee tea cafe hot drink espresso morning brew', cat: 'food' },
  { emoji: '🍵', name: 'tea green matcha drink hot herbal cup', cat: 'food' },
  { emoji: '🍣', name: 'sushi Japanese seafood rice salmon dinner', cat: 'food' },
  { emoji: '🍜', name: 'ramen noodle soup broth Asian hot bowl', cat: 'food' },
  { emoji: '🍩', name: 'donut doughnut sweet dessert bakery glaze', cat: 'food' },
  { emoji: '🍪', name: 'cookie biscuit sweet chocolate bakery snack', cat: 'food' },
  { emoji: '🍰', name: 'cake slice dessert sweet bakery birthday', cat: 'food' },
  { emoji: '🍎', name: 'apple fruit healthy red snack fresh vitamin', cat: 'food' },
  { emoji: '🥑', name: 'avocado fruit green healthy salad food', cat: 'food' },
  { emoji: '🍉', name: 'watermelon fruit melon summer fresh juicy', cat: 'food' },
  { emoji: '🍓', name: 'strawberry berry fruit sweet red fresh', cat: 'food' },
  { emoji: '🍿', name: 'popcorn movie cinema snack corn butter', cat: 'food' },
  // Transport & Vehicles
  { emoji: '🚀', name: 'rocket spaceship space launch transport speed fly fast', cat: 'transport' },
  { emoji: '🛸', name: 'ufo flying saucer alien space scifi aircraft', cat: 'transport' },
  { emoji: '🚗', name: 'car automobile vehicle drive road travel', cat: 'transport' },
  { emoji: '🏎️', name: 'racecar fast formula speed sports motorsport', cat: 'transport' },
  { emoji: '🏍️', name: 'motorcycle bike motorbike speed ride driver', cat: 'transport' },
  { emoji: '🚲', name: 'bicycle bike cycle eco fitness transport pedal', cat: 'transport' },
  { emoji: '✈️', name: 'airplane plane flight travel journey sky airport', cat: 'transport' },
  { emoji: '🚁', name: 'helicopter rotor fly aircraft air mission rescue', cat: 'transport' },
  { emoji: '⛵', name: 'sailboat boat ocean sea wind marine voyage', cat: 'transport' },
  { emoji: '🚢', name: 'ship cruise boat cargo sea ocean voyage', cat: 'transport' },
  { emoji: '🚆', name: 'train transit rail railway commute locomotive', cat: 'transport' },
  { emoji: '🛹', name: 'skateboard skate sport street board trick', cat: 'transport' },
  // Characters & People
  { emoji: '🧑‍🚀', name: 'astronaut space cosmonaut explorer mission suit', cat: 'characters' },
  { emoji: '🧑‍💻', name: 'developer programmer engineer code coder tech developer', cat: 'characters' },
  { emoji: '🧙‍♂️', name: 'wizard mage sorcerer magic fantasy spell', cat: 'characters' },
  { emoji: '🤖', name: 'robot bot AI android cyborg cyber machine', cat: 'characters' },
  { emoji: '🥷', name: 'ninja stealth warrior martial shadow covert', cat: 'characters' },
  { emoji: '🦁', name: 'lion animal cat king predator brave safari', cat: 'characters' },
  { emoji: '🐯', name: 'tiger animal cat wild predator jungle stripes', cat: 'characters' },
  { emoji: '🐼', name: 'panda bear bamboo cute animal China wildlife', cat: 'characters' },
  { emoji: '🦊', name: 'fox animal wild clever red orange canine', cat: 'characters' },
  { emoji: '🦉', name: 'owl bird night wise wisdom nocturnal eyes', cat: 'characters' },
  { emoji: '🦄', name: 'unicorn horse horn magic rainbow fantasy myth', cat: 'characters' },
  { emoji: '🐲', name: 'dragon mythical beast creature monster fantasy', cat: 'characters' },
  { emoji: '🐧', name: 'penguin bird antarctic snow ice cute cold', cat: 'characters' },
  // Nature & Elements
  { emoji: '🌿', name: 'herb leaf plant green ecology nature flora eco', cat: 'nature' },
  { emoji: '🌲', name: 'pine tree forest evergreen wood nature wood', cat: 'nature' },
  { emoji: '🌸', name: 'cherry blossom flower pink spring sakura bloom', cat: 'nature' },
  { emoji: '🌻', name: 'sunflower flower summer yellow bright bloom sun', cat: 'nature' },
  { emoji: '🍁', name: 'maple leaf autumn fall orange nature foliage', cat: 'nature' },
  { emoji: '🌴', name: 'palm tree beach island tropical summer resort', cat: 'nature' },
  { emoji: '🌊', name: 'wave ocean sea water tsunami surf surf water', cat: 'nature' },
  { emoji: '⛰️', name: 'mountain rock peak summit climbing snow outdoor', cat: 'nature' },
  { emoji: '🌋', name: 'volcano lava eruption mountain magma fire heat', cat: 'nature' },
  { emoji: '⚡', name: 'lightning bolt electricity energy power storm thunder', cat: 'nature' },
  { emoji: '🔥', name: 'fire flame hot burn blaze campfire heat energy', cat: 'nature' },
  { emoji: '🪐', name: 'saturn planet cosmos galaxy orbit ring astronomical', cat: 'nature' },
  { emoji: '🌟', name: 'star shining sparkle light glow galaxy bright', cat: 'nature' },
  // Activities & Games
  { emoji: '🎯', name: 'target bullseye aim goal precision arrow focus', cat: 'activities' },
  { emoji: '🎮', name: 'game controller gaming video esports play arcade', cat: 'activities' },
  { emoji: '🎲', name: 'dice boardgame gamble luck roll random chance', cat: 'activities' },
  { emoji: '🏆', name: 'trophy champion win winner cup victory contest', cat: 'activities' },
  { emoji: '🥇', name: 'medal gold first winner award victory achievement', cat: 'activities' },
  { emoji: '⚽', name: 'soccer football ball sport goal team match', cat: 'activities' },
  { emoji: '🏀', name: 'basketball ball hoop court sport NBA bounce', cat: 'activities' },
  { emoji: '🎸', name: 'guitar rock music sound band instrument play', cat: 'activities' },
  { emoji: '🎹', name: 'piano keyboard keys music melody classical jazz', cat: 'activities' },
  { emoji: '🎬', name: 'movie clapper film cinema video director hollywood', cat: 'activities' }
];
